# Require minimum iOS version for WebRTC support
platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'NovaidRemoteAssistance' do
  config = use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # WebRTC
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  # Gesture Handler
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # Reanimated
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # SVG
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'NovaidRemoteAssistanceTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native',
      :mac_catalyst_enabled => false
    )

    # Fix for Xcode 15
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end
  end
end
